using UnityEditor;
using UnityEngine;

namespace Machamy.GameplayTags.Editor
{
    /// <summary>
    /// GameplayTag 에디터 다국어 지원
    /// 런타임 디버거 로컬라이제이션 포함
    /// </summary>
    public static class GameplayTagEditorLocalization
    {
        private const string LanguagePrefKey = "GameplayTag_Language";

        public enum Language
        {
            Korean,
            English
        }

        private static Language _currentLanguage = Language.Korean;

        static GameplayTagEditorLocalization()
        {
            string savedLang = EditorPrefs.GetString(LanguagePrefKey, "Korean");
            _currentLanguage = savedLang == "English" ? Language.English : Language.Korean;
        }

        public static Language CurrentLanguage
        {
            get => _currentLanguage;
            set
            {
                _currentLanguage = value;
                EditorPrefs.SetString(LanguagePrefKey, value.ToString());
            }
        }

        public static string Get(string key)
        {
            return CurrentLanguage == Language.Korean ? GetKorean(key) : GetEnglish(key);
        }

        private static string GetKorean(string key)
        {
            return key switch
            {
                // 헤더
                "header.title" => "Gameplay Tag Manager",
                "header.subtitle" => "게임플레이 태그를 관리하고 코드를 생성합니다",

                // 툴바
                "toolbar.generateCode" => "🔄 코드 생성",
                "toolbar.reloadSystem" => "🔃 시스템 리로드",
                "toolbar.autoGenerate" => "자동 생성",
                "toolbar.language" => "🌐 언어",

                // 패널 타이틀
                "panel.assemblyTags" => "⚙️ 어셈블리 태그",
                "panel.userTags" => "📝 사용자 정의 태그",
                "panel.allTags" => "🌐 모든 태그",
                "panel.viewMode" => "📋 보기 모드",
                "panel.assemblyDesc" => "코드에서 [assembly: GameplayTagDef]로 정의된 태그입니다. 수정 불가능합니다.",
                "panel.userDesc" => "Resources 폴더의 ScriptableObject에 저장된 태그입니다. 수정 가능합니다.",
                "panel.allDesc" => "어셈블리 태그와 사용자 정의 태그를 모두 볼 수 있습니다.",
                
                // 탭
                "tab.all" => "🌐 모든 태그",
                "tab.assembly" => "⚙️ 어셈블리 태그",
                "tab.user" => "📝 사용자 정의 태그",

                // 데이터베이스
                "database.label" => "데이터베이스:",
                "database.none" => "(데이터베이스 없음)",
                "database.createNew" => "+ 새 데이터베이스",

                // 태그 추가
                "addTag.title" => "새 태그 추가",
                "addTag.name" => "태그 이름",
                "addTag.namePlaceholder" => "예: Player.Health.Max",
                "addTag.description" => "설명",
                "addTag.descPlaceholder" => "태그 설명 (선택사항)",
                "addTag.button" => "➕ 태그 추가",

                // 정렬
                "sort.label" => "정렬:",
                "sort.alphabetical" => "알파벳순",
                "sort.hierarchical" => "계층구조",
                "sort.dateAdded" => "추가된 순서",

                 // 필터
                "filter.label" => "필터:",
                "filter.showAssembly" => "어셈블리 태그 표시",
                "filter.showUser" => "사용자 태그 표시",

                // 출처
                "source.label" => "출처",
                "source.assembly" => "어셈블리",
                "source.user" => "사용자",
                "source.database" => "DB:",

                // 태그 아이템
                "tag.readOnly" => "읽기 전용",
                "tag.autoGenerated" => "자동 생성됨",
                "tag.delete" => "🗑️ 삭제",

                // 상태
                "status.ready" => "준비됨",
                "status.loading" => "로드 중...",
                "status.generating" => "코드 생성 중...",
                "status.generated" => "코드 생성 완료!",
                "status.reloading" => "시스템 리로드 중...",
                "status.reloaded" => "시스템 리로드 완료!",
                "status.tagAdded" => "태그 추가됨: {0}",
                "status.tagDeleted" => "태그 삭제됨: {0}",
                "status.databaseCreated" => "새 데이터베이스 생성 완료!",
                "status.databaseSelected" => "데이터베이스 선택: {0}",
                "status.autoGenerateOn" => "자동 생성: 활성화",
                "status.autoGenerateOff" => "자동 생성: 비활성화",

                // 툴팁
                "tooltip.generateCode" => "어셈블리에 정의된 모든 태그를 코드로 생성하고 ScriptableObject를 업데이트합니다.",
                "tooltip.reloadSystem" => "GameplayTag 시스템을 다시 로드하여 모든 데이터베이스를 갱신합니다.",
                "tooltip.createDatabase" => "Resources 폴더에 새로운 GameplayTagDatabase를 생성합니다.",
                "tooltip.addTag" => "현재 선택된 데이터베이스에 새 태그를 추가합니다.",
                "tooltip.databaseDropdown" => "편집할 데이터베이스를 선택합니다. 자동 생성된 데이터베이스는 표시되지 않습니다.",
                "tooltip.autoGenerate" => "활성화하면 스크립트 컴파일 시 자동으로 코드를 생성합니다.",
                "tooltip.tagName" => "태그 이름을 입력하세요. 예: Player.Health.Max",
                "tooltip.tagDescription" => "태그에 대한 설명을 입력하세요 (선택사항).",
                "tooltip.assemblyCount" => "어셈블리에서 발견된 태그의 총 개수입니다.",
                "tooltip.userCount" => "현재 선택된 데이터베이스의 태그 개수입니다.",
                "tooltip.assemblyList" => "코드에 [assembly: GameplayTagDef(...)]로 정의된 모든 태그 목록입니다.",
                "tooltip.userList" => "선택된 데이터베이스에 저장된 태그 목록입니다. 추가/삭제가 가능합니다.",
                "tooltip.readOnly" => "이 태그는 어셈블리 속성으로 정의되어 있어 수정할 수 없습니다.",
                "tooltip.deleteTag" => "'{0}' 태그를 데이터베이스에서 삭제합니다.",

                // 런타임 디버거
                "debugger.title" => "Gameplay Tag Runtime Debugger",
                "debugger.subtitle" => "런타임 중 등록된 게임플레이 태그를 확인하고 디버깅합니다",
                "debugger.warning" => "⚠️ 플레이 모드에서만 사용 가능합니다",
                "debugger.warningDesc" => "에디터를 플레이 모드로 전환하면 런타임 태그 정보를 확인할 수 있습니다.",
                "debugger.viewIdSort" => "🔢 ID 순",
                "debugger.viewStringSort" => "🔤 문자열 순",
                "debugger.viewTreeMode" => "🌲 트리 모드",
                "debugger.search" => "🔍 검색",
                "debugger.statusLoading" => "태그 로딩 중...",
                "debugger.statusEmpty" => "등록된 태그가 없습니다.",
                "debugger.statusCount" => "총 {0}개 태그 (검색 결과: {1}개)",
                "debugger.requestTitle" => "🔍 태그 요청 테스트",
                "debugger.requestPlaceholder" => "예: Player.Health.Max",
                "debugger.requestButton" => "태그 요청",
                "debugger.requestSuccess" => "✅ 태그 발견: ID={0}, String=\"{1}\"",
                "debugger.requestNotFound" => "❌ 태그를 찾을 수 없습니다: \"{0}\"",
                "debugger.requestError" => "❌ 오류: {0}",
                "debugger.requestEmptyField" => "❌ 태그 문자열을 입력해주세요.",
                "debugger.requestPlayModeOnly" => "❌ 플레이 모드에서만 사용 가능합니다.",
                "debugger.tagCopied" => "태그 복사됨: {0}",
                "debugger.openButton" => "🎮 런타임 디버거",

                // 다이얼로그
                "dialog.error" => "오류",
                "dialog.selectDatabase" => "데이터베이스를 선택해주세요.",
                "dialog.enterTagName" => "태그 이름을 입력해주세요.",
                "dialog.deleteTag.title" => "태그 삭제",
                "dialog.deleteTag.message" => "정말로 '{0}' 태그를 삭제하시겠습니까?",
                "dialog.delete" => "삭제",
                "dialog.cancel" => "취소",
                "dialog.ok" => "확인",

                _ => key
            };
        }

        private static string GetEnglish(string key)
        {
            return key switch
            {
                // Header
                "header.title" => "Gameplay Tag Manager",
                "header.subtitle" => "Manage gameplay tags and generate code",

                // Toolbar
                "toolbar.generateCode" => "🔄 Generate Code",
                "toolbar.reloadSystem" => "🔃 Reload System",
                "toolbar.autoGenerate" => "Auto Generate",
                "toolbar.language" => "🌐 Language",

                // Panel Titles
                "panel.assemblyTags" => "⚙️ Assembly Tags",
                "panel.userTags" => "📝 User-Defined Tags",
                "panel.allTags" => "🌐 All Tags",
                "panel.viewMode" => "📋 View Mode",
                "panel.assemblyDesc" => "Tags defined in code with [assembly: GameplayTagDef]. Read-only.",
                "panel.userDesc" => "Tags stored in ScriptableObject in Resources folder. Editable.",
                "panel.allDesc" => "View both assembly tags and user-defined tags together.",
                
                // Tabs
                "tab.all" => "🌐 All Tags",
                "tab.assembly" => "⚙️ Assembly Tags",
                "tab.user" => "📝 User-Defined Tags",

                // Database
                "database.label" => "Database:",
                "database.none" => "(No Database)",
                "database.createNew" => "+ New Database",

                // Add Tag
                "addTag.title" => "Add New Tag",
                "addTag.name" => "Tag Name",
                "addTag.namePlaceholder" => "e.g., Player.Health.Max",
                "addTag.description" => "Description",
                "addTag.descPlaceholder" => "Tag description (optional)",
                "addTag.button" => "➕ Add Tag",

                // Sort
                "sort.label" => "Sort:",
                "sort.alphabetical" => "Alphabetical",
                "sort.hierarchical" => "Hierarchical",
                "sort.dateAdded" => "Date Added",

                // Filter
                "filter.label" => "Filter:",
                "filter.showAssembly" => "Show Assembly Tags",
                "filter.showUser" => "Show User Tags",

                // Source
                "source.label" => "Source",
                "source.assembly" => "Assembly",
                "source.user" => "User",
                "source.database" => "DB:",

                // Tag Item
                "tag.readOnly" => "Read Only",
                "tag.autoGenerated" => "Auto Generated",
                "tag.delete" => "🗑️ Delete",

                // Status
                "status.ready" => "Ready",
                "status.loading" => "Loading...",
                "status.generating" => "Generating code...",
                "status.generated" => "Code generation complete!",
                "status.reloading" => "Reloading system...",
                "status.reloaded" => "System reload complete!",
                "status.tagAdded" => "Tag added: {0}",
                "status.tagDeleted" => "Tag deleted: {0}",
                "status.databaseCreated" => "New database created!",
                "status.databaseSelected" => "Database selected: {0}",
                "status.autoGenerateOn" => "Auto Generate: ON",
                "status.autoGenerateOff" => "Auto Generate: OFF",

                // Tooltips
                "tooltip.generateCode" => "Generate code for all tags defined in assemblies and update ScriptableObject.",
                "tooltip.reloadSystem" => "Reload the GameplayTag system and refresh all databases.",
                "tooltip.createDatabase" => "Create a new GameplayTagDatabase in the Resources folder.",
                "tooltip.addTag" => "Add a new tag to the currently selected database.",
                "tooltip.databaseDropdown" => "Select a database to edit. Auto-generated databases are not shown.",
                "tooltip.autoGenerate" => "When enabled, automatically generates code on script compilation.",
                "tooltip.tagName" => "Enter tag name. e.g., Player.Health.Max",
                "tooltip.tagDescription" => "Enter tag description (optional).",
                "tooltip.assemblyCount" => "Total number of tags found in assemblies.",
                "tooltip.userCount" => "Number of tags in the currently selected database.",
                "tooltip.assemblyList" => "List of all tags defined with [assembly: GameplayTagDef(...)] in code.",
                "tooltip.userList" => "Tags stored in the selected database. Can be added/deleted.",
                "tooltip.readOnly" => "This tag is defined as an assembly attribute and cannot be modified.",
                "tooltip.deleteTag" => "Delete '{0}' tag from database.",

                // Runtime Debugger
                "debugger.title" => "Gameplay Tag Runtime Debugger",
                "debugger.subtitle" => "View and debug gameplay tags registered at runtime",
                "debugger.warning" => "⚠️ Only available in Play Mode",
                "debugger.warningDesc" => "Enter Play Mode to view runtime tag information.",
                "debugger.viewIdSort" => "🔢 Sort by ID",
                "debugger.viewStringSort" => "🔤 Sort by String",
                "debugger.viewTreeMode" => "🌲 Tree Mode",
                "debugger.search" => "🔍 Search",
                "debugger.statusLoading" => "Loading tags...",
                "debugger.statusEmpty" => "No tags registered.",
                "debugger.statusCount" => "Total {0} tags (Search results: {1})",
                "debugger.requestTitle" => "🔍 Tag Request Test",
                "debugger.requestPlaceholder" => "e.g., Player.Health.Max",
                "debugger.requestButton" => "Request Tag",
                "debugger.requestSuccess" => "✅ Tag found: ID={0}, String=\"{1}\"",
                "debugger.requestNotFound" => "❌ Tag not found: \"{0}\"",
                "debugger.requestError" => "❌ Error: {0}",
                "debugger.requestEmptyField" => "❌ Please enter a tag string.",
                "debugger.requestPlayModeOnly" => "❌ Only available in Play Mode.",
                "debugger.tagCopied" => "Tag copied: {0}",
                "debugger.openButton" => "🎮 Runtime Debugger",

                // Dialog
                "dialog.error" => "Error",
                "dialog.selectDatabase" => "Please select a database.",
                "dialog.enterTagName" => "Please enter a tag name.",
                "dialog.deleteTag.title" => "Delete Tag",
                "dialog.deleteTag.message" => "Are you sure you want to delete '{0}' tag?",
                "dialog.delete" => "Delete",
                "dialog.cancel" => "Cancel",
                "dialog.ok" => "OK",

                _ => key
            };
        }

        public static string Format(string key, params object[] args)
        {
            return string.Format(Get(key), args);
        }
    }
}

