using UnityEditor;
using UnityEngine;

namespace Machamy.GameplayTags.Editor
{
    /// <summary>
    /// GameplayTagDatabase의 커스텀 인스펙터
    /// </summary>
    [CustomEditor(typeof(Runtime.GameplayTagDatabase))]
    public class GameplayTagDatabaseEditor : UnityEditor.Editor
    {
        private string _newTagName = "";
        private string _newTagDescription = "";

        public override void OnInspectorGUI()
        {
            Runtime.GameplayTagDatabase database = (Runtime.GameplayTagDatabase)target;

            EditorGUILayout.Space();
            EditorGUILayout.LabelField("게임플레이 태그 데이터베이스", EditorStyles.boldLabel);
            
            // 자동 생성된 데이터베이스 경고
            if (database.IsAutoGenerated)
            {
                EditorGUILayout.HelpBox(
                    "이 데이터베이스는 자동으로 생성된 데이터베이스입니다.\n" +
                    "수정할 수 없습니다.",
                    MessageType.Warning);
                EditorGUILayout.Space();
                bool originalState = GUI.enabled;
                GUI.enabled = false;
                DrawDefaultInspector();
                GUI.enabled = originalState;
                EditorGUILayout.Space();
                EditorGUILayout.LabelField($"총 태그 개수: {database.Tags.Count}개", EditorStyles.miniLabel);
                return;
            }
            
            EditorGUILayout.HelpBox(
                "이 데이터베이스에 등록된 태그는 게임에서 사용할 수 있습니다.\n" +
                "Resources 폴더에 저장해야 자동으로 로드됩니다.",
                MessageType.Info);

            EditorGUILayout.Space();

            // 새 태그 추가 UI
            EditorGUILayout.LabelField("새 태그 추가", EditorStyles.boldLabel);
            EditorGUILayout.BeginVertical("box");
            {
                _newTagName = EditorGUILayout.TextField("태그 이름", _newTagName);
                _newTagDescription = EditorGUILayout.TextField("설명", _newTagDescription);

                EditorGUI.BeginDisabledGroup(string.IsNullOrWhiteSpace(_newTagName));
                if (GUILayout.Button("태그 추가"))
                {
                    database.AddTag(_newTagName.Trim(), _newTagDescription);
                    _newTagName = "";
                    _newTagDescription = "";
                    GUI.FocusControl(null);
                }
                EditorGUI.EndDisabledGroup();
            }
            EditorGUILayout.EndVertical();

            EditorGUILayout.Space();

            // 기본 인스펙터 그리기
            DrawDefaultInspector();

            EditorGUILayout.Space();

            // 유틸리티 버튼들
            EditorGUILayout.BeginHorizontal();
            {
                if (GUILayout.Button("모든 태그 지우기"))
                {
                    if (EditorUtility.DisplayDialog(
                        "태그 삭제 확인",
                        "정말로 모든 태그를 삭제하시겠습니까?",
                        "삭제",
                        "취소"))
                    {
                        database.ClearTags();
                    }
                }

                if (GUILayout.Button("태그 시스템 리로드"))
                {
                    Runtime.GameplayTagManager.ReloadTags();
                    Debug.Log("게임플레이 태그 시스템이 리로드되었습니다.");
                }
            }
            EditorGUILayout.EndHorizontal();

            // 태그 개수 표시
            EditorGUILayout.Space();
            EditorGUILayout.LabelField($"총 태그 개수: {database.Tags.Count}개", EditorStyles.miniLabel);
        }
    }
}
