using System;
using System.Collections.Generic;
using System.Linq;

namespace Machamy.GameplayTags.Runtime
{
    /// <summary>
    /// 게임플레이 태그 등록 에러 정보
    /// </summary>
    public class GameplayTagRegistrationError
    {
        public string TagName { get; }
        public string Message { get; }
        public IGameplayTagSource Source { get; }

        public GameplayTagRegistrationError(string tagName, string message, IGameplayTagSource source)
        {
            TagName = tagName;
            Message = message;
            Source = source;
        }
    }

    /// <summary>
    /// 게임플레이 태그 등록 컨텍스트
    /// </summary>
    public class GameplayTagRegistrationContext
    {
        private readonly Dictionary<string, TagRegistrationData> _pendingTags = new();
        private readonly List<GameplayTagRegistrationError> _errors = new();

        private class TagRegistrationData
        {
            public string Name;
            public string Description;
            public IGameplayTagSource Source;
            public bool IsAutoGenerated => Source == null;
        }

        /// <summary>
        /// 태그를 등록합니다.
        /// </summary>
        public void RegisterTag(string tagName, string description, IGameplayTagSource source)
        {
            if (string.IsNullOrWhiteSpace(tagName))
            {
                _errors.Add(new GameplayTagRegistrationError(
                    tagName,
                    "태그 이름이 비어있거나 공백입니다.",
                    source));
                return;
            }

            // 이미 등록된 태그인지 확인
            if (_pendingTags.TryGetValue(tagName, out TagRegistrationData existing))
            {
                MergeDuplicateRegistration(existing, description, source);
                return;
            }

            // 부모 태그가 존재하는지 확인
            string parentTagName = GetParentTagName(tagName);
            if (!string.IsNullOrEmpty(parentTagName) && !_pendingTags.ContainsKey(parentTagName))
            {
                // 부모 태그 자동 생성
                // 초기화 때마다 자동 생성된 부모 수만큼 로그가 쌓이므로 기본적으로 끕니다.
                // UnityEngine.Debug.Log($"[GameplayTagRegistrationContext] 부모 태그 '{parentTagName}'를 자동 생성합니다 (자식: '{tagName}')");
                RegisterTag(parentTagName, "Auto-generated parent tag", null);
            }

            _pendingTags.Add(tagName, new TagRegistrationData
            {
                Name = tagName,
                Description = description ?? "",
                Source = source
            });
        }

        /// <summary>
        /// 이미 등록된 이름으로 등록 요청이 다시 들어왔을 때의 병합 규칙입니다.
        /// <para>
        /// 같은 정의가 두 번 들어오는 것은 오류가 아닙니다. <c>Resources.LoadAll</c>은 에디터/테스트 러너
        /// 환경에서 같은 에셋의 복제 인스턴스를 여러 번 반환하기 때문에, 소스가 정상적으로 동작해도
        /// 동일한 태그가 반복해서 등록됩니다. 정의가 실제로 충돌할 때(설명이 서로 다를 때)만 에러로 봅니다.
        /// </para>
        /// </summary>
        private void MergeDuplicateRegistration(TagRegistrationData existing, string description, IGameplayTagSource source)
        {
            // 자동 생성된 자리표시자는 실제 정의로 대체합니다.
            if (existing.IsAutoGenerated && source != null)
            {
                existing.Description = description ?? "";
                existing.Source = source;
                return;
            }

            // 자동 생성 요청은 이미 존재하는 정의를 덮지 않습니다.
            if (source == null)
                return;

            string incomingDescription = description ?? "";

            // 완전히 동일한 중복 등록 - 무시합니다.
            if (string.Equals(existing.Description, incomingDescription, StringComparison.Ordinal))
                return;

            // 한쪽만 설명이 비어있다면 채워진 쪽을 채택합니다.
            if (string.IsNullOrEmpty(existing.Description))
            {
                existing.Description = incomingDescription;
                existing.Source = source;
                return;
            }

            if (string.IsNullOrEmpty(incomingDescription))
                return;

            // 설명이 서로 다르면 어느 쪽이 옳은지 알 수 없으므로 에러로 보고합니다.
            _errors.Add(new GameplayTagRegistrationError(
                existing.Name,
                $"태그가 서로 다른 설명으로 중복 등록되었습니다. " +
                $"기존: \"{existing.Description}\" (소스: {DescribeSource(existing.Source)}), " +
                $"신규: \"{incomingDescription}\" (소스: {DescribeSource(source)})",
                source));
        }

        private static string DescribeSource(IGameplayTagSource source) => source?.Name ?? "자동생성";

        /// <summary>
        /// 등록 에러 목록을 가져옵니다.
        /// </summary>
        public IEnumerable<GameplayTagRegistrationError> GetRegistrationErrors()
        {
            return _errors;
        }

        /// <summary>
        /// 등록된 태그들로부터 태그 정의를 생성합니다.
        /// </summary>
        internal List<GameplayTagSpec> GenerateDefinitions()
        {
            var definitions = new List<GameplayTagSpec>();
            
            definitions.Add(new GameplayTagSpec("None", "Empty Tag", 0, null));
            
            var sortedTags = _pendingTags.Values.OrderBy(t => t.Name);
            
            int id = 1;
            var definitionLookup = new Dictionary<string, GameplayTagSpec>();
            
            foreach (var tagData in sortedTags)
            {
                var definition = new GameplayTagSpec(
                    tagData.Name,
                    tagData.Description,
                    id++,
                    tagData.Source);

                definitions.Add(definition);
                definitionLookup[tagData.Name] = definition;
            }
            
            foreach (var definition in definitions.Skip(1)) 
            {
                string parentTagName = GetParentTagName(definition.TagName);
                if (!string.IsNullOrEmpty(parentTagName) && definitionLookup.TryGetValue(parentTagName, out var parent))
                {
                    definition.SetParent(parent);
                }
            }

            return definitions;
        }

        private string GetParentTagName(string tagName)
        {
            int lastDotIndex = tagName.LastIndexOf('.');
            if (lastDotIndex > 0)
            {
                return tagName.Substring(0, lastDotIndex);
            }
            return null;
        }
    }
}

