using System.Collections.Generic;
using System.Linq;

namespace Machamy.GameplayTags.Runtime
{
    /// <summary>
    /// 게임플레이 태그 등록 에러 정보
    /// </summary>
    public class GameplayTagRegistrationError
    {
        public string TagName { get; }
        public string Message { get; }
        public IGameplayTagSource Source { get; }

        public GameplayTagRegistrationError(string tagName, string message, IGameplayTagSource source)
        {
            TagName = tagName;
            Message = message;
            Source = source;
        }
    }

    /// <summary>
    /// 게임플레이 태그 등록 컨텍스트
    /// </summary>
    public class GameplayTagRegistrationContext
    {
        private readonly Dictionary<string, TagRegistrationData> _pendingTags = new();
        private readonly List<GameplayTagRegistrationError> _errors = new();

        private class TagRegistrationData
        {
            public string Name;
            public string Description;
            public IGameplayTagSource Source;
            public bool IsAutoGenerated => Source == null;
        }

        /// <summary>
        /// 태그를 등록합니다.
        /// </summary>
        public void RegisterTag(string tagName, string description, IGameplayTagSource source)
        {
            if (string.IsNullOrWhiteSpace(tagName))
            {
                _errors.Add(new GameplayTagRegistrationError(
                    tagName,
                    "태그 이름이 비어있거나 공백입니다.",
                    source));
                return;
            }

            // 이미 등록된 태그인지 확인
            if (_pendingTags.ContainsKey(tagName))
            {
                if (_pendingTags[tagName].IsAutoGenerated && source != null)
                {
                    // 자동 생성된 태그를 실제 태그로 대체
                    _pendingTags[tagName].Description = description;
                    _pendingTags[tagName].Source = source;
                }
                else
                {
                    // 중복 등록 에러
                    _errors.Add(new GameplayTagRegistrationError(
                        tagName,
                        "태그가 이미 등록되어 있습니다.",
                        source));
                }

                
                return;
            }
            
            // 부모 태그가 존재하는지 확인
            string parentTagName = GetParentTagName(tagName);
            if (!string.IsNullOrEmpty(parentTagName) && !_pendingTags.ContainsKey(parentTagName))
            {
                // 부모 태그 자동 생성
                UnityEngine.Debug.Log($"[GameplayTagRegistrationContext] 부모 태그 '{parentTagName}'를 자동 생성합니다 (자식: '{tagName}')");
                RegisterTag(parentTagName, "Auto-generated parent tag", null);
            }

            _pendingTags.Add(tagName, new TagRegistrationData
            {
                Name = tagName,
                Description = description,
                Source = source
            });
        }

        /// <summary>
        /// 등록 에러 목록을 가져옵니다.
        /// </summary>
        public IEnumerable<GameplayTagRegistrationError> GetRegistrationErrors()
        {
            return _errors;
        }

        /// <summary>
        /// 등록된 태그들로부터 태그 정의를 생성합니다.
        /// </summary>
        internal List<GameplayTagSpec> GenerateDefinitions()
        {
            var definitions = new List<GameplayTagSpec>();
            
            definitions.Add(new GameplayTagSpec("None", "Empty Tag", 0, null));
            
            var sortedTags = _pendingTags.Values.OrderBy(t => t.Name);
            
            int id = 1;
            var definitionLookup = new Dictionary<string, GameplayTagSpec>();
            
            foreach (var tagData in sortedTags)
            {
                var definition = new GameplayTagSpec(
                    tagData.Name,
                    tagData.Description,
                    id++,
                    tagData.Source);

                definitions.Add(definition);
                definitionLookup[tagData.Name] = definition;
            }
            
            foreach (var definition in definitions.Skip(1)) 
            {
                string parentTagName = GetParentTagName(definition.TagName);
                if (!string.IsNullOrEmpty(parentTagName) && definitionLookup.TryGetValue(parentTagName, out var parent))
                {
                    definition.SetParent(parent);
                }
            }

            return definitions;
        }

        private string GetParentTagName(string tagName)
        {
            int lastDotIndex = tagName.LastIndexOf('.');
            if (lastDotIndex > 0)
            {
                return tagName.Substring(0, lastDotIndex);
            }
            return null;
        }
    }
}

