using System;
using System.Collections.Generic;
using UnityEngine;

namespace Machamy.GameplayTags.Runtime
{
    /// <summary>
    /// Resources 폴더에서 로드되는 게임플레이 태그 데이터베이스
    /// </summary>
    [CreateAssetMenu(fileName = "GameplayTagDatabase", menuName = "Gameplay Tags/Tag Database")]
    public class GameplayTagDatabase : ScriptableObject
    {
        [Serializable]
        public class TagEntry
        {
            [SerializeField] private string tagName;
            [SerializeField, TextArea(1, 3)] private string description;

            public string TagName => tagName;
            public string Description => description;

            public TagEntry(string tagName, string tagDescription = "")
            {
                this.tagName = tagName;
                description = tagDescription;
            }
        }
        // [Header("Auto-generated Gameplay Tag Database")]
        [SerializeField,HideInInspector] bool isAutoGenerated;
 
        [Header("태그 목록")]
        [SerializeField] private List<TagEntry> tags = new();

        
        /// <summary>
        /// 자동 생성된 데이터베이스인지 여부
        /// </summary>
        public bool IsAutoGenerated
        {
            get => isAutoGenerated;
#if UNITY_EDITOR
            set => isAutoGenerated = value;
#endif
        }
        
        /// <summary>
        /// 태그 목록을 가져옵니다.
        /// </summary>
        public IReadOnlyList<TagEntry> Tags => tags;

        /// <summary>
        /// 태그를 추가합니다 (에디터 전용).
        /// </summary>
        public void AddTag(string tagName, string tagDescription = "")
        {
#if UNITY_EDITOR
            if (isAutoGenerated)
            {
                Debug.LogWarning("자동 생성된 데이터베이스는 수정할 수 없습니다.");
                return;
            }

            if (string.IsNullOrEmpty(tagName))
            {
                Debug.LogWarning("태그 이름이 비어있습니다.");
                return;
            }

            // 중복 체크
            if (tags.Exists(t => t.TagName == tagName))
            {
                Debug.LogWarning($"태그가 이미 존재합니다: {tagName}");
                return;
            }

            tags.Add(new TagEntry(tagName, tagDescription));
            UnityEditor.EditorUtility.SetDirty(this);
#endif
        }

        /// <summary>
        /// 태그를 제거합니다 (에디터 전용).
        /// </summary>
        public void RemoveTag(string tagName)
        {
#if UNITY_EDITOR
            if (isAutoGenerated)
            {
                Debug.LogWarning("자동 생성된 데이터베이스는 수정할 수 없습니다.");
                return;
            }

            int removed = tags.RemoveAll(t => t.TagName == tagName);
            if (removed > 0)
            {
                UnityEditor.EditorUtility.SetDirty(this);
            }
#endif
        }

        /// <summary>
        /// 모든 태그를 지웁니다 (에디터 전용).
        /// </summary>
        public void ClearTags()
        {
#if UNITY_EDITOR
            if (isAutoGenerated)
            {
                Debug.LogWarning("자동 생성된 데이터베이스는 수정할 수 없습니다.");
                return;
            }

            tags.Clear();
            UnityEditor.EditorUtility.SetDirty(this);
#endif
        }

        #region Internal Auto-Generation Methods
        
        /// <summary>
        /// 자동 생성 시스템 전용: 모든 태그를 지웁니다 (IsAutoGenerated 체크 무시)
        /// CAUTION: 에디터 전용 내부 메서드입니다. 직접 호출하지 마세요.
        /// </summary>
        public void InternalClearTags()
        {
#if UNITY_EDITOR
            tags.Clear();
#endif
        }

        /// <summary>
        /// 자동 생성 시스템 전용: 태그를 추가합니다 (IsAutoGenerated 체크 무시)
        /// CAUTION: 에디터 전용 내부 메서드입니다. 직접 호출하지 마세요.
        /// </summary>
        public void InternalAddTag(string tagName, string tagDescription = "")
        {
#if UNITY_EDITOR
            if (string.IsNullOrEmpty(tagName))
            {
                Debug.LogWarning("태그 이름이 비어있습니다.");
                return;
            }

            // 중복 체크
            if (tags.Exists(t => t.TagName == tagName))
            {
                Debug.LogWarning($"태그가 이미 존재합니다: {tagName}");
                return;
            }

            tags.Add(new TagEntry(tagName, tagDescription));
#endif
        }
        
        #endregion
    }
}

