using UnityEditor;
using UnityEngine;
using System.IO;

namespace Machamy.GameplayTags.Editor
{
    /// <summary>
    /// 게임플레이 태그 관련 에디터 메뉴
    /// </summary>
    public static class GameplayTagEditorMenu
    {
        private const string ResourcesFolderPath = "Assets/Resources";
        private const string DefaultDatabaseName = "GameplayTagDatabase";
        private const string MenuRoot = "Tools/Gameplay Tags/";

        [MenuItem(MenuRoot + "Open Tag Manager ⚙️", priority = 0)]
        public static void OpenTagManager()
        {
            GameplayTagEditor.ShowWindow();
        }

        [MenuItem(MenuRoot + "Create Tag Database", priority = 100)]
        public static void CreateTagDatabase()
        {
            // Resources 폴더가 없으면 생성
            if (!AssetDatabase.IsValidFolder(ResourcesFolderPath))
            {
                string parentFolder = "Assets";
                AssetDatabase.CreateFolder(parentFolder, "Resources");
            }

            // 데이터베이스 생성
            Runtime.GameplayTagDatabase database = ScriptableObject.CreateInstance<Runtime.GameplayTagDatabase>();

            // 고유한 파일 이름 생성
            string assetPath = AssetDatabase.GenerateUniqueAssetPath(
                $"{ResourcesFolderPath}/{DefaultDatabaseName}.asset");

            // 에셋 생성
            AssetDatabase.CreateAsset(database, assetPath);
            AssetDatabase.SaveAssets();

            // 생성된 에셋 선택 및 포커스
            EditorUtility.FocusProjectWindow();
            Selection.activeObject = database;

            Debug.Log($"[GameplayTag] 데이터베이스 생성됨: {assetPath}");
        }

        [MenuItem(MenuRoot + "Settings/Generate Code Now", priority = 200)]
        public static void GenerateCodeNow()
        {
            GameplayTagCodeGenerator.GenerateCodeStatic();
        }

        [MenuItem(MenuRoot + "Settings/Toggle Auto Generate", priority = 201)]
        public static void ToggleAutoGenerate()
        {
            bool current = EditorPrefs.GetBool("GameplayTag_AutoGenerate", true);
            EditorPrefs.SetBool("GameplayTag_AutoGenerate", !current);
            Debug.Log($"[GameplayTag] 자동 생성: {(!current ? "활성화" : "비활성화")}");
        }

        [MenuItem(MenuRoot + "Settings/Toggle Auto Generate", true)]
        public static bool ToggleAutoGenerateValidate()
        {
            bool current = EditorPrefs.GetBool("GameplayTag_AutoGenerate", true);
            Menu.SetChecked(MenuRoot + "Settings/Toggle Auto Generate", current);
            return true;
        }

        [MenuItem(MenuRoot + "Settings/Reload Tag System", priority = 202)]
        public static void ReloadTagSystem()
        {
            Runtime.GameplayTagManager.ReloadTags();
            Debug.Log("[GameplayTag] 태그 시스템 리로드 완료");
        }

        [MenuItem(MenuRoot + "Debug/Show All Tags", priority = 300)]
        public static void ShowAllTags()
        {
            var tags = Runtime.GameplayTagManager.GetAllTags();
            
            if (tags.Length == 0)
            {
                Debug.Log("[GameplayTag] 등록된 태그가 없습니다.");
                return;
            }

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine($"=== 등록된 게임플레이 태그 ({tags.Length}개) ===");
            
            foreach (var tag in tags)
            {
                sb.AppendLine($"- {tag.TagName}");
            }

            Debug.Log(sb.ToString());
        }

        [MenuItem(MenuRoot + "Debug/Validate Databases", priority = 301)]
        public static void ValidateResourcesDatabases()
        {
            // Resources 폴더의 모든 GameplayTagDatabase 찾기
            var databases = Resources.LoadAll<Runtime.GameplayTagDatabase>("");

            if (databases.Length == 0)
            {
                Debug.LogWarning("[GameplayTag] Resources 폴더에 데이터베이스가 없습니다.");
                return;
            }

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine($"=== GameplayTagDatabase 검증 결과 ({databases.Length}개 발견) ===");

            int totalTags = 0;
            foreach (var db in databases)
            {
                string path = AssetDatabase.GetAssetPath(db);
                sb.AppendLine($"\n데이터베이스: {db.name}");
                sb.AppendLine($"  경로: {path}");
                sb.AppendLine($"  태그 개수: {db.Tags.Count}개");
                sb.AppendLine($"  자동 생성: {(db.IsAutoGenerated ? "예" : "아니오")}");

                totalTags += db.Tags.Count;

                // 중복 체크
                System.Collections.Generic.HashSet<string> tagNames = new();
                foreach (var tag in db.Tags)
                {
                    if (!tagNames.Add(tag.TagName))
                    {
                        sb.AppendLine($"  ⚠️ 중복 태그 발견: {tag.TagName}");
                    }
                }
            }

            sb.AppendLine($"\n총 태그 개수: {totalTags}개");
            Debug.Log(sb.ToString());
        }
    }
}

